kafka:
  bootstrap-servers: localhost:9092
  taxiride:
    topic: taxirides
    partition-count: 1
    replication-factor: 1
  taxiridestart:
    topic: taxiridestarts
    partition-count: 1
    replication-factor: 1
  intermediateprice:
    topic: intermediateprices
    partition-count: 1
    replication-factor: 1
  taxirideend:
    topic: taxirideends
    partition-count: 1
    replication-factor: 1